use std::collections::{HashMap, VecDeque};

use crate::clean_lines;

pub fn run(input: &str) -> usize {
    let mut modules = parse_input(input);

    let mut button_press_pulse_count = vec![];
    let mut cycle_length = 0;

    loop {
        button_press_pulse_count.push(button_press(&mut modules));
        cycle_length += 1;

        if cycle_length == 1000 || is_cycle_completed(&modules) {
            break;
        }
    }

    let multiplier = 1000 / cycle_length;
    let remainder = 1000 % cycle_length;

    let cycle_pulse_count = button_press_pulse_count
        .clone()
        .into_iter()
        .reduce(|acc, count| (acc.0 + count.0, acc.1 + count.1))
        .unwrap();
    let mut remainder_pulse_count = (0, 0);
    if remainder > 0 {
        remainder_pulse_count = (0..remainder)
            .map(|i| button_press_pulse_count[i])
            .reduce(|acc, count| (acc.0 + count.0, acc.1 + count.1))
            .unwrap();
    }

    (cycle_pulse_count.0 * multiplier + remainder_pulse_count.0)
        * (cycle_pulse_count.1 * multiplier + remainder_pulse_count.1)
}

/// Checks whether all modules are reset to initial state.
fn is_cycle_completed<'a>(modules: &HashMap<&'a str, Module<'a>>) -> bool {
    modules.values().all(|module| match &module.module_type {
        ModuleType::FlipFlop { state } => !state,
        ModuleType::Conjunction { inputs } => inputs.values().all(|b| !*b),
        _ => true,
    })
}

/// Sends the initial pulse from button to broadcaster.
///
/// Returns the number of (low pulses, high pulses) generated by the button press.
fn button_press<'a>(modules: &mut HashMap<&'a str, Module<'a>>) -> (usize, usize) {
    let (mut low_signals, mut high_signals) = (1, 0);

    let mut signals = VecDeque::new();
    signals.push_back(Signal {
        predecessor: "button",
        successor: "broadcaster",
        pulse: false,
    });

    while !signals.is_empty() {
        let signal = signals.pop_front().unwrap();

        let mut outputs = modules
            .get(signal.successor)
            .unwrap()
            .clone()
            .process_pulse(signal, modules);

        let count = outputs.len();
        if count > 0 {
            if outputs[0].pulse {
                high_signals += count;
            } else {
                low_signals += count;
            }
        }

        signals.append(&mut outputs);
    }

    (low_signals, high_signals)
}

pub(crate) fn parse_input(input: &str) -> HashMap<&str, Module> {
    let mut modules = HashMap::new();

    // Populate the modules first.
    clean_lines(input).map(Module::from).for_each(|module| {
        modules.insert(module.name, module);
    });

    // Post-processing, update the conjunction inputs, and create any unknown modules.
    for module in modules.clone().values() {
        for output in &module.outputs {
            if let Some(successor) = modules.get(output) {
                if let ModuleType::Conjunction { inputs } = &successor.module_type {
                    let mut inputs = inputs.clone();
                    inputs.insert(module.name, false);
                    modules.insert(
                        successor.name,
                        Module {
                            name: successor.name,
                            module_type: ModuleType::Conjunction { inputs },
                            outputs: successor.outputs.clone(),
                        },
                    );
                }
            } else {
                modules.insert(
                    output,
                    Module {
                        name: output,
                        module_type: ModuleType::Unknown,
                        outputs: vec![],
                    },
                );
            }
        }
    }

    modules
}

#[derive(PartialEq)]
/// A pulse sent by a predecessor module to a successor module.
pub(crate) struct Signal<'a> {
    pub(crate) predecessor: &'a str,
    pub(crate) successor: &'a str,
    pub(crate) pulse: bool,
}

#[derive(Clone)]
pub(crate) enum ModuleType<'a> {
    Unknown,
    FlipFlop { state: bool },
    Conjunction { inputs: HashMap<&'a str, bool> },
    Broadcaster,
}

#[derive(Clone)]
pub(crate) struct Module<'a> {
    pub(crate) name: &'a str,
    module_type: ModuleType<'a>,
    outputs: Vec<&'a str>,
}

impl<'a> Module<'a> {
    /// Processes a signal from a predecessor.
    ///
    /// Updates oneself in modules, and returns a list of Signals to send out to successors.
    pub(crate) fn process_pulse(
        mut self,
        input: Signal<'a>,
        modules: &mut HashMap<&'a str, Module<'a>>,
    ) -> VecDeque<Signal<'a>> {
        let mut outputs = VecDeque::new();

        if let ModuleType::FlipFlop { state } = self.module_type {
            match input.pulse {
                true => (),
                false => {
                    self.module_type = ModuleType::FlipFlop { state: !state };
                    outputs = self
                        .outputs
                        .iter()
                        .map(|module| Signal {
                            predecessor: self.name,
                            successor: module,
                            pulse: !state,
                        })
                        .collect();
                }
            }
        }

        if let ModuleType::Conjunction { inputs } = &mut self.module_type {
            inputs.insert(input.predecessor, input.pulse);

            let pulse = !inputs.values().all(|b| *b);
            outputs = self
                .outputs
                .iter()
                .map(|module| Signal {
                    predecessor: self.name,
                    successor: module,
                    pulse,
                })
                .collect();
        }

        if let ModuleType::Broadcaster = self.module_type {
            outputs = self
                .outputs
                .iter()
                .map(|module| Signal {
                    predecessor: self.name,
                    successor: module,
                    pulse: input.pulse,
                })
                .collect();
        }

        modules.insert(self.name, self);

        outputs
    }
}

impl<'a> From<&'a str> for Module<'a> {
    fn from(value: &'a str) -> Self {
        let (name_part, outputs_part) = value.split_once(" -> ").unwrap();

        let (name, module_type) = match name_part {
            "broadcaster" => ("broadcaster", ModuleType::Broadcaster),
            _ if &name_part[0..1] == "%" => {
                (&name_part[1..], ModuleType::FlipFlop { state: false })
            }
            _ if &name_part[0..1] == "&" => (
                &name_part[1..],
                ModuleType::Conjunction {
                    inputs: HashMap::new(),
                },
            ),
            _ => (name_part, ModuleType::Unknown),
        };

        let outputs = outputs_part.split(", ").collect::<Vec<&str>>();

        Self {
            name,
            module_type,
            outputs,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn run_example() {
        let input = r"
            broadcaster -> a, b, c
            %a -> b
            %b -> c
            %c -> inv
            &inv -> a
        ";
        assert_eq!(run(input), 32000000);

        let input = r"
            broadcaster -> a
            %a -> inv, con
            &inv -> b
            %b -> con
            &con -> output
        ";
        assert_eq!(run(input), 11687500);
    }
}
